# Generated by Django 2.2.7 on 2019-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=200)),
                ('category_gif', models.CharField(max_length=200)),
                ('category_description', models.TextField()),
            ],
        ),
    ]
